### ISSUE TITLE
Page dectecting accuracy is not good

### ISSUE THREAD

**Issue by Shiv162003** [Shiv162003/Braille_vision#1]
i need a light weight model that is able to detect a page and is able to crop that page out of the entire image .
i need a function in which 
1- input an image and returns image of a page without any background 448*448 image

**Comment by pratyushagrawal77** [comment]
Implement function to crop and resize page from image using YOLOv8
- Added `crop_page` function to detect and crop a page from an image.
- Applied YOLOv8 model to identify the page and created a binary mask.
- Cropped the detected page region and resized the output to 448x448 pixels.

**Comment by pratyushagrawal77** [comment]
Implement function to crop and resize page from image using YOLOv8

- Added `crop_page` function to detect and crop a page from an image.
- Applied YOLOv8 model to identify the page and created a binary mask.
- Cropped the detected page region and resized the output to 448x448 pixels.

**Comment by pratyushagrawal77** [comment]
Implement function to crop and resize page from image using YOLOv8

- Added `crop_page` function to detect and crop a page from an image.
- Applied YOLOv8 model to identify the page and created a binary mask.
- Cropped the detected page region and resized the output to 448x448 pixels.
